import { generatePaletteCandidate } from "./generator.js";
import {
  COLOR_GENERATION_REQUEST_SCHEMA,
  type DecorativeCandidateFamily,
  type NamedPaletteName,
  type NamedPaletteReference,
  type TwelveStepScale,
} from "./types.js";

export const NAMED_PALETTE_NAMES = [
  "gray",
  "mauve",
  "slate",
  "sage",
  "olive",
  "sand",
  "tomato",
  "red",
  "ruby",
  "crimson",
  "pink",
  "plum",
  "purple",
  "violet",
  "iris",
  "indigo",
  "blue",
  "cyan",
  "teal",
  "jade",
  "green",
  "grass",
  "lime",
  "mint",
  "sky",
  "gold",
  "bronze",
  "brown",
  "yellow",
  "amber",
  "orange",
] as const satisfies readonly NamedPaletteName[];

// These are FLOWSTACK anchors, not semantic assignments. Each named raw
// reference is generated by the same qualified decorative algorithm exposed
// to every consumer.
const NAMED_PALETTE_SEEDS = {
  gray: "#6b7280",
  mauve: "#7f6f7d",
  slate: "#64748b",
  sage: "#6b7d6b",
  olive: "#787a45",
  sand: "#8a7967",
  tomato: "#e54d2e",
  red: "#dc2626",
  ruby: "#e11d48",
  crimson: "#c2185b",
  pink: "#db2777",
  plum: "#a43cb5",
  purple: "#7c3aed",
  violet: "#6d28d9",
  iris: "#5b5bd6",
  indigo: "#4f46e5",
  blue: "#2563eb",
  cyan: "#0891b2",
  teal: "#0d9488",
  jade: "#059669",
  green: "#16a34a",
  grass: "#65a30d",
  lime: "#84cc16",
  mint: "#10b981",
  sky: "#0ea5e9",
  gold: "#b7791f",
  bronze: "#9c6644",
  brown: "#8b5e3c",
  yellow: "#eab308",
  amber: "#f59e0b",
  orange: "#f97316",
} as const satisfies Record<NamedPaletteName, string>;

export function isNamedPaletteName(value: string): value is NamedPaletteName {
  return (NAMED_PALETTE_NAMES as readonly string[]).includes(value);
}

export function getNamedPalette(name: NamedPaletteName): NamedPaletteReference {
  if (!isNamedPaletteName(name)) {
    throw new TypeError(`Unknown named palette ${JSON.stringify(name)}.`);
  }
  const seed = NAMED_PALETTE_SEEDS[name];
  const candidate = generatePaletteCandidate({
    $schema: COLOR_GENERATION_REQUEST_SCHEMA,
    seeds: [{
      id: name,
      color: seed,
      profile: "decorative",
      options: { steps: 12, anchorStep: 9 },
    }],
  });
  const family = candidate.families[0] as DecorativeCandidateFamily;
  if (family.status !== "accepted") {
    const reasons = family.diagnostics
      .filter((diagnostic) => diagnostic.severity === "error")
      .map((diagnostic) => diagnostic.code)
      .join(", ");
    throw new Error(
      `FLOWSTACK named palette '${name}' failed decorative qualification: ${reasons}.`,
    );
  }
  const light = family.appearances.light?.steps.map((step) => step.srgb.hex);
  const dark = family.appearances.dark?.steps.map((step) => step.srgb.hex);
  if (light?.length !== 12 || dark?.length !== 12) {
    throw new Error(`FLOWSTACK named palette '${name}' did not produce 12 steps.`);
  }
  return {
    name,
    seed,
    light: light as unknown as TwelveStepScale,
    dark: dark as unknown as TwelveStepScale,
    qualification: "raw-reference",
    source: {
      name: "@flowstack-ui/colors",
      algorithm: "flowstack-palette-v1",
    },
  };
}
